
-- 
-- Editor server script for DB table kirimbarang
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `kirimbarang` (
	`id` int(10) NOT NULL auto_increment,
	`nokirimbarang` varchar(255) default NULL,
	`namabarang` varchar(255) default NULL,
	`noijinperusahaan` varchar(255) default NULL,
	`noijinjasa` varchar(255) default NULL,
	`idprovkirim` varchar(255) default NULL,
	`idprovdari` varchar(255) default NULL,
	`pegawaijasapengirim` varchar(255) default NULL,
	`pegawaitelkompenerima` varchar(255) default NULL,
	`date` timestamp,
	`alamatkirim` text default NULL,
	`statuskirim` varchar(255) default NULL,
	`statusterima` varchar(255) default NULL,
	PRIMARY KEY  (`id`)
);

